Implement basic book controller
RomanYuzviak/OnlineBookStore pull request #2
Opened 2023-10-19 22:46 UTC by RomanYuzviak

2023-10-20 06:06 UTC, Cayman4010 commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +    }
As I remember we need to delete this bean

2023-10-20 06:07 UTC, Cayman4010 commented on src/main/java/com/example/onlinebookstore/mapper/BookMapper.java
> +@Mapper(config = MapperConfig.class)
you can add configuration just here, without additional config

2023-10-20 06:10 UTC, Cayman4010 commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can not get all books from database", ex);
You should use the custom EntityNotFoundException

2023-10-20 06:10 UTC, Cayman4010 commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can not get book by id %d from database".formatted(id), ex);
here too

2023-10-20 06:11 UTC, Cayman4010 requested changes
Good job! But you can improve your code! :)

2023-10-24 15:29 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +    private BookService bookService;
Do you need this service here?

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/mapper/BookMapper.java
> +@Mapper(config = MapperConfig.class)
```suggestion
@Mapper(componentModel = "spring",
        injectionStrategy = InjectionStrategy.CONSTRUCTOR,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        implementationPackage = "<PACKAGE_NAME>.impl")
```

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/mapper/BookMapper.java
> +    Book toModel(CreateBookRequestDto bookDto);
toBook will be better

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +public class Book {
Add Table annotation

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +    Optional<Book> get(Long id);
bad naming
findById

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +    @Autowired
You don't need Autowired here as you have one constructor
Also, be consistent and you can use RequiredArgsConstructor annotation like in BookServiceImpl

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Can not create the book: " + book, ex);
It's better to create one more custom exception DataProcessingException and throw it here

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +    public Optional<Book> get(Long id) {
rename

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/BookService.java
> +    BookDto get(Long id);
```suggestion
    BookDto findById(Long id);
```

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.get(id).orElseThrow(() ->
This code is really hard to read. Also bad idea to throw RuntimeException
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Can't find book with id " + id));
        return bookMapper.toDto(book);
```

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
use record from Java 17

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/BookDto.java
> +public class BookDto {
use record from Java 17

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +@RequestMapping(value = "/api/books")
```suggestion
@RequestMapping(value = "/books")
```

2023-10-24 15:29 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/config/MapperConfig.java
> +public class MapperConfig {
remove class as you will replace config to BookMapper

2023-11-06 09:58 UTC, NazarSmith228 requested changes
Everything seems to be fine, but you need to resolve the merge conflicts

2023-11-08 00:36 UTC, merged