Spring data features added
RomanYuzviak/OnlineBookStore pull request #3
Opened 2023-10-24 14:47 UTC by RomanYuzviak

2023-10-25 11:11 UTC, AlexVulpine requested changes
Good job! Let's improve your solution

2023-10-25 11:11 UTC, AlexVulpine commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: numeric
Suggest adding a constraint nullable: false

2023-10-25 11:11 UTC, AlexVulpine commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +                new RuntimeException("There is not book in db by id %d"
Use your EntityNotFoundException here

2023-10-25 11:11 UTC, AlexVulpine commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +            throw new RuntimeException("There is not book in db by id %d"
Use your EntityNotFoundException here also

2023-10-25 11:11 UTC, AlexVulpine commented on src/main/java/com/example/onlinebookstore/mapper/BookMapper.java
> +@Mapper(config = MapperConfig.class)
I'd suggest putting the config info directly here, bc we won't need a very detailed config for mapper.

2023-10-25 11:11 UTC, AlexVulpine commented on src/main/java/com/example/onlinebookstore/mapper/BookMapper.java
> +    Book toModel(CreateBookRequestDto bookDto);
It's better to change name to "toBook" to be more concise as we will have more classes in model package in the future.

2023-10-25 11:11 UTC, AlexVulpine commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    }
You could use RequiredArgsConstructor annotation from lombok to get rid of this.

2023-10-25 11:11 UTC, AlexRosenkreuz commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    public BookDto findById(@PathVariable Long id) {
suggest naming it getById

2023-10-25 11:11 UTC, AlexRosenkreuz commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +        return bookService.update(id, requestDto);
You also need @ResponseStatus(HttpStatus.ACCEPTED) here

2023-10-25 11:11 UTC, AlexRosenkreuz commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    }
As we added CreateBookRequest for implementing Create endpoint suggest naming it createBook. You also need to add annotation with ResponseStatus

2023-10-25 11:11 UTC, AlexRosenkreuz commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +    private BookService bookService;
Better make it final

2023-10-25 11:11 UTC, AlexRosenkreuz commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +
Redundant lines

2023-10-31 09:27 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-31 09:27 UTC, NazarSmith228 commented on pom.xml
> +        <lombok.version>1.18.30</lombok.version>
this is redundant - lombok is  inherited from `spring-boot-starter-parent`

2023-10-31 09:27 UTC, NazarSmith228 commented on pom.xml
> +            <version>${liquibase.version}</version>
this is a plugin

therefore it should be removed from dependencies section

2023-10-31 09:27 UTC, NazarSmith228 commented on pom.xml
> +            <version>${liquibase.version}</version>
no need to specify the version here - it is taken from `spring-boot-starter-parent`

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +    private BookService bookService;
why do you need it here?

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.ACCEPTED)
HTTP 202 ACCEPTED is wrong here

HTTP 202 means that a request was accepted for processing but hasn't been processed yet - the processing should happen in the nearest future

in our case update is executed immediately, thus we need to use HTTP 200 OK

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/dto/BookDto.java
> +public class BookDto {
please use records for DTO

if there is a problem with Checkstyle - upgrade the checkstyle-plugin to 3.3.0

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
please use records for DTO

if there is a problem with Checkstyle - upgrade the checkstyle-plugin to 3.3.0

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    @Column(nullable = false)
shouldn't you specify `name = "is_deleted" here?

will it work as it is?

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +
redundant blank line

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Long> {
`@Repository` is missing

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +                .formatted(id))));
you may simplify the setup here a bit:
```
return repo.findById(id)
       .map(mapper::toDto)
       .orElseThrow(...);
```

2023-10-31 09:27 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(updatedBook));
bad approach

you should fetch the desired book by id, then update it, and save afterwards

you can leverage Mapstruct to perform update:
```
void updateBook(CreateBookRequestDto  dto, @MappingTarget Book book);
```

the final version will be like:
```
Book book = repo.findById(id).orElseThrow(...);
mapper.updateBook(dto, book);
return mapper.toDto(repo.save(book));
```

2023-11-26 23:55 UTC, RomanYuzviak commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    @Column(nullable = false)
Yes, It works

2023-11-27 14:57 UTC, Elena-Bruyako approved these changes
Good job! Left one comment.

2023-11-27 14:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +    private BookService bookService;
Remove unused service

2023-11-27 23:43 UTC, merged