Pagination sorting swagger implemented
RomanYuzviak/OnlineBookStore pull request #5
Opened 2023-10-25 20:42 UTC by RomanYuzviak

2023-10-26 10:31 UTC, don-bigdad approved these changes
nice

2023-10-27 07:24 UTC, Elena-Bruyako requested changes
Good job! 
There are conflicts in your branch, need to resolve them. 
Also, try to figure out how to merge your previous changes. Because in every your PRs I see the same code from previous PR with the same mistakes.

2023-10-27 07:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +//swagger doc http://localhost:8080/swagger-ui/index.html#/
Remove comment

2023-10-27 07:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +@Tag(name = "Book CRUD API", description = "Endpoints to manage books")
```suggestion
@Tag(name = "Book store API", description = "Endpoints to manage books")
```

2023-10-27 07:24 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @GetMapping
It's better to add @Operation for all endpoints

2023-11-29 11:33 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-11-29 11:33 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Do you really need both annotations? you already have `spring-boot-starter-validation`

2023-11-30 00:09 UTC, merged