Security implemented
RomanYuzviak/OnlineBookStore pull request #6
Opened 2023-11-07 02:30 UTC by RomanYuzviak

2023-11-08 08:55 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-08 08:55 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
you don't need these dependencies

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/controller/AuthenticationController.java
> +    public UserResponseDto register(
makes sense to add CREATED response status

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/controller/AuthenticationController.java
> +@Validated
you don't need this annotation here

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
you may simplify 
```suggestion
    @PreAuthorize("hasRole('USER')")
```

`hasRole` automatically adds `ROLE_` prefix

apply to all places

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/dto/user/UserLoginRequestDto.java
> +) {
```suggestion
        String password) {
```

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +) {
```suggestion
        String repeatedPassword) {
```

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    @ManyToMany
pls exclude it from equals/hashcode and to string to avoid lazy loading

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/repository/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
`@Repository` is missing

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
`@Repository` is missing

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/security/AuthenticationService.java
> +        final Authentication authentication = authenticationManager.authenticate(
```suggestion
        Authentication authentication = authenticationManager.authenticate(
```

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username) {
```

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String authorizationHeader = request.getHeader("Authorization");
pls use existing constant `org.springframework.http.HttpHeaders.AUTHORIZATION`

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return authorizationHeader.substring(7);
consider declaring a constant
```suggestion
        if (authorizationHeader != null && authorizationHeader.startsWith(BEARER_TYPE)) {
            return authorizationHeader.substring(BEARER_TYPE.length());
```

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
consider declaring `boolean existsByEmail(String email)` method in repository

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/validation/FieldsMatchValidator.java
> +                .getPropertyValue(repeatedField);
can you use a single `BeanWrapperImpl`?

2023-11-08 08:55 UTC, NazarSmith228 commented on src/main/java/com/example/onlinebookstore/validation/FieldsMatchValidator.java
> +        }
you can simplify this with `Objects.equals()`

2023-11-28 00:41 UTC, RomanYuzviak commented on pom.xml
> +        </dependency>
I need config dependency

2023-11-28 00:53 UTC, RomanYuzviak commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String authorizationHeader = request.getHeader("Authorization");
This field doesn`t exist in the class you pointed

2023-11-29 15:23 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +        @Size(min = 2, max = 32) @NotNull
`@NotBlank` is better for String

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/exception/DataProcessingException.java
> +
remove empty line

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/exception/EntityNotFoundException.java
> +
the same

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/exception/EntityNotFoundException.java
> +
do you need empty line here?

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/mapper/UserMapper.java
> +
remove empty line

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Role.java
> +    public enum RoleName {
it's better to replace inner enum in the end of class

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String authorizationHeader = request.getHeader("Authorization");
There is a constant for such cases in Spring 

org.springframework.http.HttpHeaders.AUTHORIZATION

Check the link of docs [Spring docs](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html#AUTHORIZATION)

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +    public static final String BEARER_TYPE = "Bearer";
```suggestion
    public static final String BEARER_TYPE = "Bearer ";
```

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return authorizationHeader.substring(BEARER_TYPE.length() + 1);
```suggestion
            return authorizationHeader.substring(BEARER_TYPE.length());
```

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/UserServiceImpl.java
> +        user.getRoles().add(roleRepository.findByName(Role.RoleName.ROLE_USER));
```suggestion
        user.setRoles(Set.of(roleRepository.findByName(Role.RoleName.ROLE_USER)));
```

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/validation/FieldsMatchValidator.java
> +
remove empty line

2023-11-29 15:23 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
please check that size of fields the same as in requests

2023-12-01 09:55 UTC, liliia-ponomarenko approved these changes
Good job! But please fix comments before merging ;)

2023-12-01 09:55 UTC, liliia-ponomarenko commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String authorizationHeader = request.getHeader("Authorization");
not fixed

2023-12-01 09:55 UTC, liliia-ponomarenko commented on src/main/java/com/example/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +        @Size(min = 2, max = 32) @NotNull
not fixed

2023-12-03 16:38 UTC, merged