Order model
RomanYuzviak/OnlineBookStore pull request #9
Opened 2023-12-05 00:28 UTC by RomanYuzviak

2023-12-05 07:02 UTC, KDanil2000 approved these changes
LGMT!

2023-12-06 08:53 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/OrderController.java
> +
```suggestion
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/OrderController.java
> +    public List<OrderDto> getAll(Pageable pageable, Principal principal) {
You can use Authentication authentication like method parameter, then getting user by
User user = (User) authentication.getPrincipal();
and use user.getId();

it's avoid unnecessary query to database in method private Long getUserId(Principal principal) {

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/OrderController.java
> +    public List<OrderItemDto> getAllItems(@PathVariable @Positive Long orderId, Pageable pageable) {
```suggestion
    public List<OrderItemDto> getAllItems(@PathVariable @Positive Long orderId, @ParameterObject @PageableDefault Pageable pageable) {
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/order/OrderUpdateDto.java
> +
```suggestion
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/order/OrderUpdateDto.java
> +public record OrderUpdateDto(
It's request or response?

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/order/OrderRequestDto.java
> +        String shippingAddress
Do you need Size annotation?

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/mapper/OrderMapper.java
> +
```suggestion
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +@Data
```suggestion
@Getter
@Setter
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +    @ToString.Exclude
```suggestion
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "book_id", nullable = false)
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +@Data
```suggestion
@Getter
@Setter
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ToString.Exclude
```suggestion
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/repository/OrderRepository.java
> +public interface OrderRepository extends JpaRepository<Order, Long> {
`@Repository`

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/dto/order/OrderUpdateDto.java
> +        String shippingAddress,
you don't need shippingAddress in this request. The requirements are said about update status

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public OrderDto update(OrderRequestDto requestDto, Long userId) {
Why you have two update methods? What is the logic about?

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +
```suggestion
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(
```suggestion
        return orderMapper.toDto(orderRepository.save(currentOrder));
```

2023-12-06 08:53 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/mapper/OrderItemMapper.java
> +
```suggestion
```

2023-12-11 00:01 UTC, RomanYuzviak commented on src/main/java/com/example/onlinebookstore/dto/order/OrderUpdateDto.java
> +        String shippingAddress,
I thought it`ll be good to allow admin to change an address

2023-12-11 07:18 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-12-11 07:18 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +    @ManyToOne(fetch = FetchType.LAZY, optional = false)
`@JoinColumn(name = "user_id", nullable = false)`

2023-12-11 07:18 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ManyToOne(fetch = FetchType.LAZY, optional = false)
`@JoinColumn(name = "order_id", nullable = false)`

2023-12-11 07:18 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ManyToOne(fetch = FetchType.LAZY, optional = false)
`@JoinColumn(name = "book_id", nullable = false)`

2023-12-11 07:18 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +
remove empty line

2023-12-11 07:18 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(
```suggestion
        return orderMapper.toDto(orderRepository.save(newOrder));
```

2023-12-14 10:22 UTC, liliia-ponomarenko approved these changes
Great! But fix the conflict before merging;)

2024-01-12 15:38 UTC, closed without merging